### ISSUE TITLE
java.lang.IllegalArgumentException: No package found.

### ISSUE THREAD

**Issue by DevPriyankaOps** [FRI-DAY/sonar-gosu-plugin#124]
Hello! I'm attempting to scan a project repository that includes Gosu code. Up to this point, I've placed the sonar-communitygosu-plugin-1.2.1.jar file into the plugin directory of Sonarqube (./extensions/plugins). After restarting Sonarqube, a new Quality Profile for Gosu, including all the plugin rules, became available in Quality Profiles. However, when I scan my project, I encounter the "No package found" error. I've attached the console logs for reference. This issue is currently impeding my progress, and any assistance would be greatly appreciated. Thank you!

10:12:43.720 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalArgumentException: No package found.
	at de.friday.sonarqube.gosu.plugin.rules.smells.UnnecessaryImportRule.getClassName(UnnecessaryImportRule.java:149)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at de.friday.sonarqube.gosu.plugin.rules.smells.UnnecessaryImportRule.exitStart(UnnecessaryImportRule.java:94)
	at de.friday.sonarqube.gosu.antlr.GosuParser$StartContext.exitRule(GosuParser.java:236)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:408)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:642)
	at de.friday.sonarqube.gosu.antlr.GosuParser.start(GosuParser.java:292)
	at de.friday.sonarqube.gosu.plugin.GosuFileParser.parseFile(GosuFileParser.java:74)
	at de.friday.sonarqube.gosu.plugin.GosuFileParser.parse(GosuFileParser.java:54)
	at de.friday.sonarqube.gosu.plugin.GosuSensor.scanFile(GosuSensor.java:126)
	at de.friday.sonarqube.gosu.plugin.GosuSensor.scan(GosuSensor.java:91)
	at de.friday.sonarqube.gosu.plugin.GosuSensor.execute(GosuSensor.java:80)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:79)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:384)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:380)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:349)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by DevPriyankaOps** [comment]
Hello!! Any quick help on this would be really appreciated!!

**Comment by matey-jack** [comment]
From the stack trace it looks like a parsing error. Could you possibly narrow down to which file it is parsing at that point?

**Comment by matey-jack** [comment]
If there is really a problem with a missing package, maybe you can find that by running the Gosu compiler over the code? Or it could be a problem with the set up of source sets in your project...

**Comment by DevPriyankaOps** [comment]
Hello Jack,

I appreciate your reply to this thread. When you mention compiling the code, are you referring to the actual building of the code? If so, my source code lacks the gradlew file, as we don't utilize gradlew for code building. Consequently, I'm unable to build the code within my GitHub Actions workflow. Nevertheless, the sole purpose of this workflow is to scan the code. We rely on Jenkins to build the artifact from the source code.

**Comment by DevPriyankaOps** [comment]
Hello Jack! I'm encountering a "package not found" error, and it seems to be linked to the rule "Track unnecessary import statements." This rule is causing the scan to fail prematurely. Ideally, I'd like the error to be thrown without interrupting the entire scan. Is there a way to let the rule work without causing the job to fail early or without deactivating it? @josimar-silva  @komasztania @web-flow @gustavoreynaldofriday

**Comment by josimar-silva** [comment]
Hi @DevPriyankaOps! 
This issue was fixed by https://github.com/FRI-DAY/sonar-gosu-plugin/pull/97.
Currently is not released yet, it will be released in the next release v1.2.2. 

In the meantime, you can [build the plugin from the source](https://github.com/FRI-DAY/sonar-gosu-plugin?tab=readme-ov-file#sonarqube-on-premise) and use the snapshot version.

**Comment by josimar-silva** [comment]
Hey @DevPriyankaOps . 

The version v1.2.2 is out: https://github.com/FRI-DAY/sonar-gosu-plugin/releases/tag/v1.2.2
